### ISSUE TITLE
Close doc buffers on tab close?

### ISSUE THREAD

**Issue by ZzAntares** [powerman/vim-plugin-viewdoc#39]
Hello, thanks for this plugin, I've been using it for quite a long time, but there was something that started to annoying me but never tried to solve it, until now...

I do like that viewdoc opens the help on a new tab, when I'm done reading the doc, I close the tab, this gets me back to where I was before opening viewdoc, (this is fine), but what I don't want is that the Doc buffer is still open, even that the tab was closed, the doc is still in the buffer list thus me changing buffers I'll change back to the viewdoc buffer which I don't want to see.

Is there a way to kill the doc buffer when closing the tab? something like:

```
on :tabclose if filetype is one of ["help", "man" "pman"] then :bd Doc1
```

Thanks!

**Comment by powerman** [comment]
Well, if you close tab with doc by pressing `q` - there is no buffer left. What is actually done is `bwipeout`: https://github.com/powerman/vim-plugin-viewdoc/blob/master/plugin/viewdoc.vim#L293
I suppose problem is you're manually typing `:tabclose<Enter>` instead of just `q`.

**Comment by ZzAntares** [comment]
Oh yes you're right, pressing `q` will do the right thing, what happens is that I have a mapping to use `Ctrl+a d` as `:q`, do you know what I need to do to still use this mapping on help buffers? I tried this with no success:

`autocmd Filetype help,man,pman nnoremap <buffer> <C-a>d :bwipeout` but the mapping is the same when I'm not in a help buffer.

**Comment by powerman** [comment]
Maybe just map this to `q`?

**Comment by powerman** [comment]
AFAIR there is some extra mapping command or option in Vim which let map to some other mapping which also should be processes (this may not be default behaviour to avoid mapping loops).

**Comment by coven** [comment]
Alex Efros writes:
> AFAIR there is some extra mapping command or option in Vim which let map  
> to some other mapping which also should be processes (this may not be  
> default behaviour to avoid mapping loops).

Actually this it the „default” behaviour (the one of map command) and no  
further processing is „special” (noremap command).

**Comment by ZzAntares** [comment]
Thanks a lot, I didn't realize that I could do a simple maping (recursive) to `q`, for others interested:

I use `Ctrl+a` as an activator to manipulate windows and buffer changing, same as in `screen` or  `byobu` softwares. So I had this mapping:

```
map <C-a>d :q<CR>
```

As I said, this didn't work with help buffers, so the keep it working was add another mapping for this cases:

```
autocmd Filetype help,man,pman map <buffer> <C-a>d q
```

Thanks!
