### ISSUE TITLE
ViewDocInfo performance issue

### ISSUE THREAD

**Issue by critiqjo** [powerman/vim-plugin-viewdoc#42]
Steps to reproduce:
1. Execute `:ViewDocInfo` (without args)
2. Find `psktool` under `System Administration` section
3. Press enter.

In my system, it wasn't able to find that page, which is fine (GNU Info wasn't able to either -- simply opens its man page instead).

But now, my Vim (also Neovim) performance gets bad. Pressing `j` and `k` keys have a noticeable lag (50-100ms maybe).

If I execute `:ViewDocInfo` again, everything gets back to normal.

This strange phenomena might even be a vim-bug!

**Update**: Even executing `:ViewDocHelp` or `:ViewDocMan man` can get everything back to normal. I guess anything `ViewDoc` related will do... (Opening a random file has no effect)

**Comment by powerman** [comment]
My section looks this way:
```
System administration
* Which: (which).               Show full path of commands.
* parted: (parted).             GNU partitioning software

```
and both commands exists. I was able to find non-existing info doc in for "mpc" here:
```
GNU Packages
* Aspell: (aspell).             GNU Aspell spelling checker
* Aspell-dev: (aspell-dev).     For Aspell developers
* mpc: (mpc)Multiple Precision Complex Library.

```
after pressing Enter on mpc menu item I got empty buffer with error in status line "Sorry, no doc for (mpc)Multiple Precision Complex Library" - as expected. After switching to another window (with or without closing that doc window) I didn't notice any slowdown while editing text in that another window.

I'm using Vim (not Gvim or Neovim) 7.4.827.

**Comment by critiqjo** [comment]
I couldn't replicate it in another machine (one was too fast to experience a lag even if there was one, and in another, I couldn't find an invalid entry)... May be this is a non-issue. Closing for now, until more reliable evidence is found...

**Comment by critiqjo** [comment]
I found the cause! It was due to enabling `history_yank` source of Unite.vim. It registered an `au CursorMoved` which was the culprit.
