### ISSUE TITLE
Make vim-plugin-viewdoc respect $MANWIDTH and &winwidth

### ISSUE THREAD

**Issue by phongvcao** [powerman/vim-plugin-viewdoc#43]
Hi,

I am very impressed with the plugin. One minor issue: When viewing man pages, pydoc, perldoc, etc., `vim-plugin-viewdoc` doesn't seem to respect `$MANWIDTH` or `&winwidth`. Is there anyway I can narrow the output of `vim-plugin-viewdoc` to 80 columns for all doc types?

**Comment by powerman** [comment]
It is already support `&winwidth` for man https://github.com/powerman/vim-plugin-viewdoc/blob/master/plugin/viewdoc_man.vim#L49 and perldoc https://github.com/powerman/vim-plugin-viewdoc/blob/master/plugin/viewdoc_perldoc.vim#L88.
