### ISSUE TITLE
Can you use <Plug> instead of trying to replace <F1> and K mappings?

### ISSUE THREAD

**Issue by denilsonsa** [powerman/vim-plugin-viewdoc#44]
Some plugins, [such as easymotion](https://github.com/easymotion/vim-easymotion/blob/master/plugin/EasyMotion.vim#L240), use `<Plug>` to map to commands, and then the user can map any key to such `<Plug>`.

For instance, in case o easymotion, I can write this on my `.vimrc`:

```vim
map s <Plug>(easymotion-prefix)
map sa <Plug>(easymotion-jumptoanywhere)
map sl <Plug>(easymotion-bd-jk)
map sn <Plug>(easymotion-bd-n)
map sN <Plug>(easymotion-bd-n)
map s. <Plug>(easymotion-repeat)
map s, <Plug>(easymotion-next)
map s; <Plug>(easymotion-prev)
```

I wish I could do the same for *viewdoc*. But I can't, unless I copy [a very large and convoluted piece of code](https://github.com/powerman/vim-plugin-viewdoc/blob/4cc5ca7be00fa4f5c65cbab04dc1c5f96fdf322a/plugin/viewdoc.vim#L50) inside my `.vimrc`.

I have not tried this code, but I expected something like this:

```vim
if g:viewdoc_copy_to_search_reg
	inoremap <silent><Plug>(viewdoc-new) <C-O>:let @/ = '\<'.expand('<cword>').'\>'<CR><C-O>:call ViewDoc('new', '<cword>')<CR>
	nnoremap <silent><Plug>(viewdoc-new)      :let @/ = '\<'.expand('<cword>').'\>'<CR>:call ViewDoc('new', '<cword>')<CR>
	nnoremap <silent><Plug>(viewdoc-doc)      :let @/ = '\<'.expand('<cword>').'\>'<CR>:call ViewDoc('doc', '<cword>')<CR>
else
	inoremap <silent><Plug>(viewdoc-new) <C-O>:call ViewDoc('new', '<cword>')<CR>
	nnoremap <silent><Plug>(viewdoc-new)      :call ViewDoc('new', '<cword>')<CR>
	nnoremap <silent><Plug>(viewdoc-doc)      :call ViewDoc('doc', '<cword>')<CR>
endif
if !exists('g:no_plugin_maps') && !exists('g:no_viewdoc_maps')
	inoremap <F1> <Plug>(viewdoc-new)
	nnoremap <F1> <Plug>(viewdoc-new)
	nnoremap K    <Plug>(viewdoc-doc)
endif
```

Can you please experiment with this and see if this works? I wish to use viewdoc, but I want to change the default mappings.

**Comment by powerman** [comment]
It looks like all you need is to add into .vimrc this (replace `<F1>` and `K` with your mappings):
```vim
let g:no_viewdoc_maps=1
imap <F1> <C-O>:call ViewDoc('new', '<cword>')<CR>
nmap <F1> :call ViewDoc('new', '<cword>')<CR>
nmap K    :call ViewDoc('doc', '<cword>')<CR>
```

**Comment by denilsonsa** [comment]
I have not tried, but from my understanding, by doing so I would be ignoring the `g:viewdoc_copy_to_search_reg` value. Am I correct?

**Comment by powerman** [comment]
Yep. But it's yours vimrc, you don't need conditionals there - if you need "copy to search reg" feature with these mappings then just use corresponding (yeah, a bit longer) commands in your mappings, if you don't need it - use simpler commands I've shown above.

The point is, you can use custom mappings with viewdoc. If you wanna make these mappings looks more funny like in your examples - it's an open source, just implement this and open a pull request.
