### ISSUE TITLE
Error when opening man pages

### ISSUE THREAD

**Issue by olmokramer** [powerman/vim-plugin-viewdoc#47]
When I open a man page with `:ViewDocMan` I get the following error:

```
:ViewDocMan pipe
Error detected while processing function man#init_pager:
line    2:
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
Error detected while processing /usr/share/nvim/runtime/syntax/man.vim:
line   29:
E121: Undefined variable: b:man_sect
E15: Invalid expression: b:man_sect =~# '^[23]'
```

This also happens when I pass a section, e.g. `:ViewDocMan 2 pipe` or `:ViewDocMan pipe(2)` (which I thought might solve it, because the error is that `b:man_sect` is not set), when I use the `:ViewDoc` command, e.g. `:ViewDoc pipe man` or using the `K` keybinding on the word `pipe` in a `C` file. Other filetypes than `man` seem to work just fine. 

Oddly enough, when I press any key to close the error message, the requested man page shows just fine...

#### Versions
- viewdoc: the master branch
- Neovim: 0.2.0 (from the Arch Linux repository)

#### Viewdoc config
```vim
let g:viewdoc_open = 'topleft new'
let g:viewdoc_openempty = 0
```

**Comment by powerman** [comment]
In vim-8.0.0106 there is no error, so I suppose it's neovim issue. I don't have neovim, so I can't debug this. If you'll find a solution which doesn't break anything in vim - I'll merge it. BTW, issue might be in neovim itself, not in this plugin.

**Comment by olmokramer** [comment]
Okay, I'll see if I can find something. Thanks.

**Comment by olmokramer** [comment]
Ok, I've figured out why this happens. ViewDoc sets `nomodifiable` before setting the filetype, but NeoVim changed the man syntax files, and now the syntax depends on the buffer still being modifiable... So I'll close this issue and file one with NeoVim, because IMO syntax relying on the modifiability of a buffer is ridiculous.

Still, if you want to fix this in your plugin as well, you can apply this patch:

```diff
--- viewdoc.vim.orig	2017-05-30 15:27:38.670644655 +0200
+++ viewdoc.vim	2017-05-30 15:27:54.456200511 +0200
@@ -122,9 +122,9 @@
 			break
 		endif
 	endfor
+	execute 'setlocal ft=' . h.ft
 	setlocal nomodifiable nomodified
 
-	execute 'setlocal ft=' . h.ft
 	let b:topic = h.topic
 	if exists('h.tags')
 		execute 'setlocal tags^=' . h.tags
```

**Comment by powerman** [comment]
Thanks. I agree with you, but the fix looks harmless, so I believe it should be applied to improve compatibility. If you'll make PR and add comment which points to this issue I'll be happy to merge.

**Comment by olmokramer** [comment]
Fair enough :) I'll make the PR right away, and here's the link to the issue at @neovim repo: https://github.com/neovim/neovim/issues/6828
