### ISSUE TITLE
Provide a setting so docs open in dedicated buffer by default

### ISSUE THREAD

**Issue by ForgottenUmbrella** [powerman/vim-plugin-viewdoc#49]
Although I could just use the bang variations of the commands, e.g. `:h! foo` to open documentation in an already existing help window, I think users are used to `:h foo` opening in a dedicated buffer by default. That is, instead of opening in another "DocN" buffer, there would only be one "Doc" buffer.

I request that a setting be provided that makes the commands open in a dedicated buffer as expected. Yes, I could just get used to `:h! foo`, but that's one more keystroke than usual.

**Comment by powerman** [comment]
When you wanna modify keystroke to type in vim you can add something like this in your .vimrc:
```vim
cnoreabbrev <expr> h getcmdtype()==':' && getcmdline()=='h' ? 'ViewDocHelp!' : 'h'
```

ViewDoc already have two sets of hotkeys (`K` and `F1`) and two sets of command (with/without `!`) to choose between single "Doc" and multiple "DocN" buffers. Adding a setting which will switch meaning of these will add a lot of confusion. For example, I'll have to require people mention value of this settings in issue reports. So, I don't like this idea for now. If you can solve your issue in your vimrc then it's probably best way to go.

**Comment by ForgottenUmbrella** [comment]
I understand. I believe this abbreviation will do the trick, thanks!
