### ISSUE TITLE
Consider adding BufReadCmd's to make the plugin more Session friendly.

### ISSUE THREAD

**Issue by blankname** [powerman/vim-plugin-viewdoc#52]

**Comment by powerman** [comment]
Can you please be more specific, what exactly you need?

**Comment by blankname** [comment]
Currently if you save a session while a viewdoc window is open and try to restore that session, you'll end up with a blank buffer named [Doc].
BufReadCmd autocommands could be used to instead restore the doc that was open.

This would, I believe, require changing the naming of viewdoc buffers to contain information about which doc was open in that buffer.

For vim docs it could be something like this:
```
au BufReadCmd ViewDocHelp://* exe 'ViewDocHelp ' . split(expand('<amatch>'), 'ViewDocHelp://')[0]
```

**Comment by powerman** [comment]
I'm not sure is it good idea. ViewDoc's buffers are not supposed to be restored - it's arguable is doc opened while previous session is useful in next session. This is similar to `quickfix` buffers - they also usually restored with empty content or not restored at all. ViewDoc uses `setlocal buftype=nofile` for it's buffers to make it easier for plugins like Session to [detect and wipe such buffers](https://github.com/powerman/vim-plugin-autosess/blob/master/plugin/autosess.vim#L44) when restoring session, like autosess plugin does.

Maybe it's worth to make ViewDoc buffers more persistent with session restore support, but this should be configurable feature disabled by default and it'll require some amount of work - so I'll be happy to accept PR with this feature, but unlikely I'll have time to implement it myself.
