### ISSUE TITLE
macOS issue: E227: mapping already exists for <80>k1

### ISSUE THREAD

**Issue by reportaman** [powerman/vim-plugin-viewdoc#55]
I get the following error message when I try to launch vim or neovim on macOS with this plugin enabled:

```
Error detected while processing /Users/amanmehra/.vim/plugged/vim-plugin-viewdoc/plugin/viewdoc.vim:
line   60:
E227: mapping already exists for <80>k1
Press ENTER or type command to continue
```

Also, pressing just ``q`` does not exit the help page, I need to press one more key after that for it to exit the help page.

**Comment by powerman** [comment]
> E227: mapping already exists for <80>k1

This one is easy: you already have mapping for `<F1>` in NORMAL mode, i.e. your vimrc or one of previously loaded plugins contains something like `nmap <F1> …`. You can try to unmap it in vimrc before loading viewdoc.

> Also, pressing just `q` does not exit the help page

This one isn't that easy - `q` works for me, but I'm using Linux and also chances are your vim version may be very different to mine (8.2.0814). So, you'll probably have to do some more debugging on your side - try to disable all other plugins and check your vimrc don't do anything related to mapping `q` as a first step.

**Comment by reportaman** [comment]
@powerman Awesome! Yes I remapped a mapping to <F2> instead, and you are correct I had a mapping for ``q<something>``. Both the issues are now gone, thanks!
